import store from '../state/store.js';
import { openModal, closeModal } from './modals.js';
import { showToast } from './toasts.js';

const alertDetails = {
  'Respiratory illness surge — Eastern District (+34% WoW)': {
    severity: 'critical',
    severityLabel: 'Critical',
    description: 'Influenza A (H3N2) cases in the Eastern District have risen 34% week-over-week, crossing the emergency threshold of 400/100k population. Current rate is 512/100k. AI model forecasts continued escalation without immediate intervention.',
    actions: [
      'Activate Tier 2 respiratory surge protocol immediately',
      'Deploy rapid antigen testing to 12 community sites in Eastern District',
      'Issue public health advisory targeting high-risk groups (65+, immunocompromised)',
      'Pre-position antiviral stockpile at Eastern District General Hospital'
    ],
    population: 'Est. 47,000 residents at elevated risk'
  },
  'Vaccine coverage gap — Rural Zone B (<68%)': {
    severity: 'warning',
    severityLabel: 'Warning',
    description: 'Influenza vaccination coverage in Rural Zone B has dropped to 68%, well below the 85% herd immunity target. This leaves approximately 4,200 residents unprotected, particularly concerning given rising ILI rates in neighbouring districts.',
    actions: [
      'Deploy 3 mobile vaccination units to Rural Zone B within 72 hours',
      'Identify and contact high-risk unvaccinated residents (65+, chronic conditions)',
      'Partner with community organisations for outreach in hard-to-reach areas',
      'Consider incentive programme to increase vaccination uptake'
    ],
    population: 'Est. 4,200 unvaccinated at-risk residents'
  },
  'Wastewater SARS-CoV-2 signal elevated — Sector 4': {
    severity: 'warning',
    severityLabel: 'Warning',
    description: 'SARS-CoV-2 viral load in Sector 4 wastewater has increased 22% week-over-week to 8.1 copies/mL. Based on historical correlation data, this signal typically precedes clinical case increases by 8–12 days, suggesting a potential surge around 16–20 April.',
    actions: [
      'Pre-position additional testing capacity at Sector 4 community centres',
      'Alert local GPs and pharmacies to prepare for increased demand',
      'Schedule follow-up wastewater sampling within 72 hours',
      'Prepare public health communication for Sector 4 residents'
    ],
    population: 'Est. 18,000 residents in Sector 4 catchment area'
  },
  '3 AI-generated intervention plans ready for review': {
    severity: 'info',
    severityLabel: 'Action Required',
    description: '3 evidence-based intervention plans have been generated by the AI model and are awaiting clinical and operational review. These plans address the respiratory surge, vaccine coverage gap, and SDOH outreach expansion. Combined estimated impact: 7,450 lives improved.',
    actions: [
      'Review and approve/reject each intervention plan in the Population Health tab',
      'Assign implementation leads for approved interventions',
      'Set timeline milestones and resource allocation',
      'Schedule 48-hour progress review'
    ],
    population: 'Est. 7,450 individuals impacted across all interventions'
  }
};

function renderAlerts(alerts) {
  const strip = document.getElementById('alertsStrip');
  if (!strip) return;

  const dismissed = store.get('dismissedAlerts') || [];
  const visible = alerts.filter(a => !dismissed.includes(a.id));

  strip.innerHTML = `
    <strong style="font-size:12px;color:#7d5200;white-space:nowrap">
      ⚠ Active Alerts: <span class="alerts-badge">${visible.length}</span>
    </strong>
    ${visible.map(a => `
      <div class="alert-chip ${a.severity === 'critical' ? 'critical' : ''}" 
           data-alert-id="${a.id}" 
           role="button" tabindex="0" 
           aria-label="Alert: ${a.text}">
        <span class="alert-icon">${a.icon}</span> ${a.text}
      </div>
    `).join('')}
  `;

  strip.querySelectorAll('.alert-chip').forEach(chip => {
    const handler = () => showAlertModal(chip.dataset.alertId);
    chip.addEventListener('click', handler);
    chip.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); handler(); } });
  });
}

function showAlertModal(alertId) {
  const alerts = store.get('alerts') || [];
  const alert = alerts.find(a => a.id === alertId);
  if (!alert) return;

  const details = alertDetails[alert.text] || {
    severity: 'info',
    severityLabel: 'Information',
    description: 'Alert details not available.',
    actions: [],
    population: 'N/A'
  };

  const severityColors = {
    critical: 'badge-red',
    warning: 'badge-amber',
    info: 'badge-blue'
  };

  const content = `
    <div style="margin-bottom:16px">
      <span class="card-badge ${severityColors[details.severity] || 'badge-blue'}" style="font-size:12px">
        ${details.severityLabel}
      </span>
    </div>
    <p style="font-size:14px;line-height:1.6;color:var(--text-secondary);margin-bottom:16px">
      ${details.description}
    </p>
    <div style="margin-bottom:16px">
      <strong style="font-size:12px;text-transform:uppercase;letter-spacing:.6px;color:var(--text-muted)">Recommended Actions</strong>
      <ul style="margin:8px 0 0 16px;font-size:13px;line-height:1.8">
        ${details.actions.map(a => `<li>${a}</li>`).join('')}
      </ul>
    </div>
    <div style="padding:10px 14px;background:var(--bg-primary);border-radius:8px;font-size:13px">
      <strong>Affected Population:</strong> ${details.population}
    </div>
  `;

  openModal({
    title: alert.text,
    content,
    size: 'md',
    actions: [
      {
        label: 'Mark as Reviewed ✓',
        primary: true,
        onClick: () => {
          dismissAlert(alertId);
          closeModal();
        }
      },
      {
        label: 'Assign to Team',
        primary: false,
        onClick: () => {
          showToast('Assigned to District Health Team', 'success');
          closeModal();
        }
      },
      {
        label: 'View in Surveillance',
        primary: false,
        onClick: () => {
          closeModal();
          document.querySelector('[data-tab="surveillance"]')?.click();
        }
      }
    ]
  });
}

function dismissAlert(alertId) {
  const dismissed = store.get('dismissedAlerts') || [];
  if (!dismissed.includes(alertId)) {
    store.set('dismissedAlerts', [...dismissed, alertId]);
  }
  const alerts = store.get('alerts') || [];
  renderAlerts(alerts);
  showToast('Alert marked as reviewed', 'success', 3000);
}

export function initAlerts() {
  store.subscribe('alerts', alerts => renderAlerts(alerts));
  store.subscribe('dismissedAlerts', () => {
    const alerts = store.get('alerts') || [];
    renderAlerts(alerts);
  });

  const alerts = store.get('alerts') || [];
  if (alerts.length) renderAlerts(alerts);
}
